source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

group :default do
  gem 'rails', '~> 5.0.2'
  gem 'slim-rails'
  gem 'puma', '~> 3.0'
  gem 'sass-rails', '~> 5.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'coffee-rails', '~> 4.2'
  gem 'jquery-rails'
  gem 'turbolinks', '~> 5'
  gem 'jbuilder', '~> 2.5'
  gem 'therubyracer'
end

group :development do
  gem 'better_errors'
  gem 'html2slim'
  gem 'listen', '~> 3.0.5'
  gem 'mysql2'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-commands-rubocop'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :development, :test do
  gem 'annotate'
  gem 'awesome_print', require: 'ap'
  gem 'bullet'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'guard'
  gem 'guard-rubocop'
  gem 'guard-rspec'
  gem 'hirb'
  gem 'hirb-unicode-steakknife'
  gem 'pry-byebug'
  gem 'pry-coolline'
  gem 'pry-inline'
  gem 'pry-state'
  gem 'pry-doc'
  gem 'pry-rails'
end

group :test do
  gem 'capybara'
  gem 'poltergeist'
  gem 'rspec-rails'
  gem 'database_rewinder'
  gem 'simplecov'
  gem 'launchy'
  gem 'turnip'
  gem 'shoulda-matchers'
end
