default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8mb4
  collation: utf8mb4_bin
  url: <%= ENV['DATABASE_URL'] %>
  database: example_project_<%= ENV['RAILS_ENV'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
