# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e68100e629f8d4e2bfa5c9d3464cf5591359c8b0ffa9eb2c3f38d07d750e6c14a4f9cb2eb9ed1beefb6cb871ebbec4a8757ea18bb6c8752da14a02a0b0473e1

test:
  secret_key_base: 979ec980e09fa29deb7ae8fe21835515ad7e4bb3c5d24d796aeef459abd8895aacfe917fe5d362990860d0d4c70b41ffa6d6ea103ac1de4fcb40cba09f37bf1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
