# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96103439621045bfda0f0cc4b3e6b7e995d81d8a27ffd211df12cc8fcfd9b511bfebbce2644a8aa8c5d6bf7f4cc84ace499722cf37a1467a95b0f3bb17f2e934

test:
  secret_key_base: f7759a14a42c8edea536f2eba15a00daf211723902f313e66013675b87ca2d90d6a2d9e9953a0502253af3ac868122dcc2d4f98c72c576f8a6f49ba0b5ca2c11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
